yii/basic/models/Task.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "task".
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property int $creator_id
 * @property int $updater_id
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $updater
 * @property User $creator
 * @property TaskUser[] $taskUsers
 */
class Task extends \yii\db\ActiveRecord
{
	const RELATION_TASK_USERS = 'taskUsers';
	const RELATION_SHARED_USERS = 'sharedUsers';

	/**
	 * {@inheritdoc}
	 */
	public static function tableName()
	{
		return 'task';
	}

	/**
	 * {@inheritdoc}
	 */
	public function rules()
	{
		return [
			[['title', 'description'], 'required'],
			[['description'], 'string'],
			[['creator_id', 'updater_id', 'created_at', 'updated_at'], 'integer'],
			[['title'], 'string', 'max' => 255],
			[['updater_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updater_id' => 'id']],
			[['creator_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['creator_id' => 'id']],
		];
	}

	public function behaviors()
	{
		return [
			TimestampBehavior::class,
			[
				'class' => BlameableBehavior::class,
				'createdByAttribute' => 'creator_id',
				'updatedByAttribute' => 'updater_id'
			]
		];
	}

	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'title' => 'Title',
			'description' => 'Description',
			'creator_id' => 'Creator ID',
			'updater_id' => 'Updater ID',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
		];
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getUpdater()
	{
		return $this->hasOne(User::className(), ['id' => 'updater_id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getCreator()
	{
		return $this->hasOne(User::className(), ['id' => 'creator_id']);
	}

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getTaskUsers()
	{
		return $this->hasMany(TaskUser::className(), ['task_id' => 'id']);
	}

	public function getSharedUsers()
	{
		return $this->hasMany(User::className(), ['id' => 'user_id'])->via(self::RELATION_TASK_USERS);
	}

	/**
	 * {@inheritdoc}
	 * @return \app\models\query\TaskQuery the active query used by this AR class.
	 */
	public static function find()
	{
		return new \app\models\query\TaskQuery(get_called_class());
	}
}

yii/basic/controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Task;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	/**
	 * Lists all Task models.
	 * @return mixed
	 */
	public function actionIndex()
	{
		$dataProvider = new ActiveDataProvider([
			'query' => Task::find(),
		]);

		return $this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionMy()
	{
		$query = Task::find()->byCreator(Yii::$app->user->id);

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
		]);

		return $this->render('my', [
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionShared()
	{
		$query = Task::find()->byCreator(Yii::$app->user->id)->innerJoinWith(Task::RELATION_TASK_USERS);

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
		]);

		return $this->render('shared', [
			'dataProvider' => $dataProvider,
		]);
	}

	public function actionAccessed()
	{
		$query = Task::find()->innerJoinWith(Task::RELATION_TASK_USERS)->where(['user_id' => Yii::$app->user->id]);

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
		]);

		return $this->render('accessed', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Displays a single Task model.
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionView($id)
	{
		return $this->render('view', [
			'model' => $this->findModel($id),
		]);
	}

	/**
	 * Creates a new Task model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new Task();

		if ($model->load(Yii::$app->request->post()) && $model->save())
		{
			Yii::$app->session->setFlash('success', 'Задача создана');
			return $this->redirect(['task/my']);
		}

		return $this->render('create', [
			'model' => $model,
		]);
	}

	/**
	 * Updates an existing Task model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionUpdate($id)
	{
		$model = $this->findModel($id);

		if (!$model || $model->creator_id != Yii::$app->user->id)
		{
			throw new ForbiddenHttpException();
		}

		if ($model->load(Yii::$app->request->post()) && $model->save())
		{
			Yii::$app->session->setFlash('success', 'Задача обновлена');
			return $this->redirect(['task/my', 'id' => $model->id]);
		}

		return $this->render('update', [
			'model' => $model,
		]);
	}

	/**
	 * Deletes an existing Task model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete($id)
	{
		$task = Task::findOne($id);

		if (!$task || $task->creator_id != Yii::$app->user->id)
		{
			throw new ForbiddenHttpException();
		}

		$this->findModel($id)->delete();

		Yii::$app->session->setFlash('success', 'Задача удалена');

		return $this->redirect(['task/my']);
	}

	/**
	 * Finds the Task model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return Task the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = Task::findOne($id)) !== null)
		{
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

yii/basic/controllers/TaskUserController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\TaskUser;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Task;

/**
 * TaskUserController implements the CRUD actions for TaskUser model.
 */
class TaskUserController extends Controller
{
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['POST'],
				],
			],
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}


	public function actionDeleteAll($taskId)
	{
		$task = Task::findOne($taskId);

		if (!$task || $task->creator_id != Yii::$app->user->id)
		{
			throw new ForbiddenHttpException();
		}

		$task->unlinkAll(Task::RELATION_TASK_USERS, true);

		Yii::$app->session->setFlash('success', 'Доступы удалены');
		return $this->redirect(['task/shared']);
	}

	/**
	 * Creates a new TaskUser model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @return mixed
	 */
	public function actionCreate($taskId)
	{
		$task = Task::findOne($taskId);

		if (!$task || $task->creator_id != Yii::$app->user->id)
		{
			throw new ForbiddenHttpException();
		}

		$model = new TaskUser();
		$model->task_id = $taskId;

		if ($model->load(Yii::$app->request->post()) && $model->save())
		{
			Yii::$app->session->setFlash('success', 'Доступ добавлен');
			return $this->redirect(['task/shared']);
		}

		$arUsers = User::find()->where(['<>', 'id', Yii::$app->user->id])->select('username')->indexBy('id')->column();

		return $this->render('create', [
			'model' => $model,
			'arUsers' => $arUsers,
		]);
	}

	/**
	 * Deletes an existing TaskUser model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @return mixed
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		Yii::$app->session->setFlash('success', 'Доступы удалён');

		return $this->redirect(['task/shared']);
	}

	/**
	 * Finds the TaskUser model based on its primary key value.
	 * If the model is not found, a 404 HTTP exception will be thrown.
	 * @param integer $id
	 * @return TaskUser the loaded model
	 * @throws NotFoundHttpException if the model cannot be found
	 */
	protected function findModel($id)
	{
		if (($model = TaskUser::findOne($id)) !== null)
		{
			return $model;
		}

		throw new NotFoundHttpException('The requested page does not exist.');
	}
}

yii/basic/views/task/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Task */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii/basic/views/task/accessed.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Task;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Accessed tasks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

	<h1><?= Html::encode($this->title) ?></h1>

	<p>
		<?= Html::a('Create Task', ['create'], ['class' => 'btn btn-success']) ?>
	</p>

	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'columns' => [
			['class' => 'yii\grid\SerialColumn'],

			//'id',
			'title',
			'description:ntext',
			'creator.username',
			//'updater_id',
			'created_at:datetime',
			//'updated_at',

			[
				'class' => 'yii\grid\ActionColumn',
				'template' => '{view} {update} {delete} {share}',
				'buttons' => [
					'share' => function ($url, Task $model, $key)
					{
						$icon = \yii\bootstrap\Html::icon('share');
						return Html::a($icon, ['task-user/create', 'taskId' => $model->id]);
					}
				]
			],
		],
	]); ?>
</div>

yii/basic/views/task/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = 'Create Task';
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/basic/views/task/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tasks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Task', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'description:ntext',
            'creator_id',
            'updater_id',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

yii/basic/views/task/my.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Task;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'My tasks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

	<h1><?= Html::encode($this->title) ?></h1>

	<p>
		<?= Html::a('Create Task', ['create'], ['class' => 'btn btn-success']) ?>
	</p>

	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'columns' => [
			['class' => 'yii\grid\SerialColumn'],

			//'id',
			'title',
			'description:ntext',
			//'creator_id',
			//'updater_id',
			'created_at',
			'updated_at',

			[
				'class' => 'yii\grid\ActionColumn',
				'template' => '{view} {update} {delete} {share}',
				'buttons' => [
					'share' => function ($url, Task $model, $key)
					{
						$icon = \yii\bootstrap\Html::icon('share');
						return Html::a($icon, ['task-user/create', 'taskId' => $model->id]);
					}
				]
			],
		],
	]); ?>
</div>

yii/basic/views/task/shared.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Task;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Shared tasks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

	<h1><?= Html::encode($this->title) ?></h1>

	<p>
		<?= Html::a('Create Task', ['create'], ['class' => 'btn btn-success']) ?>
	</p>

	<?= GridView::widget([
		'dataProvider' => $dataProvider,
		'columns' => [
			['class' => 'yii\grid\SerialColumn'],

			//'id',
			'title',
			'description:ntext',
			//'creator_id',
			//'updater_id',
			'created_at',
			'updated_at',
			'users' => [
				'label' => 'Users',
				'content' => function (Task $model)
				{
					return implode(', ', $model->getSharedUsers()->select('username')->column());
				}
			],

			[
				'class' => 'yii\grid\ActionColumn',
				'template' => '{view} {update} {delete} {deleteAll}',
				'buttons' => [
					'deleteAll' => function ($url, Task $model, $key)
					{
						$icon = \yii\bootstrap\Html::icon('remove');
						return Html::a(
							$icon,
							['task-user/delete-all', 'taskId' => $model->id],
							[
								'data' => [
									'confirm' => 'Are you sure you want to delete this item?',
									'method' => 'post',
								]
							]
						);
					}
				]
			],
		],
	]); ?>
</div>

yii/basic/views/task/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = 'Update Task: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="task-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

yii/basic/views/task/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Tasks', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="task-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
            'creator_id',
            'updater_id',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>